apiVersion: v1

kind: Service

metadata:
  name: minipg
  labels:
    app: minipg

spec:
  type: LoadBalancer
  ports:
    - name: standard
      port: 5432
      targetPort: 5432
      protocol: TCP

  selector:
    app: minipg
